import { SaaSApp } from './types';

export const POPULAR_SAAS_CATALOG: Omit<SaaSApp, 'totalSeats' | 'activeSeats' | 'zombieSeats' | 'monthlyWaste' | 'annualWaste'>[] = [
  {
    id: 'figma',
    name: 'Figma Organization',
    category: 'Design',
    costPerSeatMonthly: 45,
    iconName: 'Figma',
    ssoSupported: true,
    appUrl: 'https://figma.com',
  },
  {
    id: 'notion',
    name: 'Notion Business',
    category: 'Productivity',
    costPerSeatMonthly: 18,
    iconName: 'FileText',
    ssoSupported: true,
    appUrl: 'https://notion.so',
  },
  {
    id: 'chatgpt-team',
    name: 'OpenAI ChatGPT Team',
    category: 'AI & Tools',
    costPerSeatMonthly: 30,
    iconName: 'Bot',
    ssoSupported: true,
    appUrl: 'https://openai.com',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot Enterprise',
    category: 'Engineering',
    costPerSeatMonthly: 39,
    iconName: 'Code2',
    ssoSupported: true,
    appUrl: 'https://github.com',
  },
  {
    id: 'linear',
    name: 'Linear Standard',
    category: 'Engineering',
    costPerSeatMonthly: 12,
    iconName: 'Kanban',
    ssoSupported: true,
    appUrl: 'https://linear.app',
  },
  {
    id: 'loom',
    name: 'Loom Enterprise',
    category: 'Communication',
    costPerSeatMonthly: 20,
    iconName: 'Video',
    ssoSupported: true,
    appUrl: 'https://loom.com',
  },
  {
    id: 'miro',
    name: 'Miro Business',
    category: 'Productivity',
    costPerSeatMonthly: 16,
    iconName: 'LayoutGrid',
    ssoSupported: true,
    appUrl: 'https://miro.com',
  },
  {
    id: 'slack',
    name: 'Slack Business+',
    category: 'Communication',
    costPerSeatMonthly: 15,
    iconName: 'MessageSquare',
    ssoSupported: true,
    appUrl: 'https://slack.com',
  },
  {
    id: 'salesforce',
    name: 'Salesforce Sales Cloud',
    category: 'Sales/CRM',
    costPerSeatMonthly: 80,
    iconName: 'TrendingUp',
    ssoSupported: true,
    appUrl: 'https://salesforce.com',
  },
  {
    id: 'hubspot',
    name: 'HubSpot Marketing Pro',
    category: 'Sales/CRM',
    costPerSeatMonthly: 50,
    iconName: 'Users',
    ssoSupported: true,
    appUrl: 'https://hubspot.com',
  },
  {
    id: 'datadog',
    name: 'Datadog APM & Logs',
    category: 'Engineering',
    costPerSeatMonthly: 35,
    iconName: 'Activity',
    ssoSupported: true,
    appUrl: 'https://datadoghq.com',
  },
  {
    id: 'canva',
    name: 'Canva for Teams',
    category: 'Design',
    costPerSeatMonthly: 10,
    iconName: 'Palette',
    ssoSupported: true,
    appUrl: 'https://canva.com',
  },
  {
    id: 'zoom',
    name: 'Zoom Workplace Pro',
    category: 'Communication',
    costPerSeatMonthly: 15.99,
    iconName: 'PhoneCall',
    ssoSupported: true,
    appUrl: 'https://zoom.us',
  },
  {
    id: 'postman',
    name: 'Postman Professional',
    category: 'Engineering',
    costPerSeatMonthly: 29,
    iconName: 'Send',
    ssoSupported: true,
    appUrl: 'https://postman.com',
  },
  {
    id: 'claude-team',
    name: 'Anthropic Claude Team',
    category: 'AI & Tools',
    costPerSeatMonthly: 30,
    iconName: 'Sparkles',
    ssoSupported: true,
    appUrl: 'https://claude.ai',
  }
];
