import React from 'react';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { SlashLogo } from '@/components/Logo';

export const metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for SlashSaaS.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-zinc-100 selection:bg-white selection:text-black">
      <header className="border-b border-white/[0.08] bg-zinc-950/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="mx-auto max-w-5xl px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link href="/">
            <SlashLogo size="md" />
          </Link>
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-zinc-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            <span>Back to Home</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-4 sm:px-6 py-16">
        <div className="mb-12 border-b border-white/[0.08] pb-8">
          <h1 className="text-3xl sm:text-5xl font-black text-white tracking-tight">
            Terms of Service
          </h1>
          <p className="text-sm text-zinc-400 mt-2">
            Last Updated: September 5, 2026 • Effective Immediately
          </p>
        </div>

        <div className="space-y-8 text-sm text-zinc-300 leading-relaxed font-normal">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">1. Acceptance of Terms</h2>
            <p>
              By accessing or using <strong>SlashSaaS (slashsaas.com)</strong>, you agree to comply with and be bound by these Terms of Service. If you are using our services on behalf of an organization, you represent that you have authority to bind that entity.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">2. What SlashSaaS Provides</h2>
            <p>
              SlashSaaS is an AI search visibility monitoring service. You configure public brand names, competitors, and prompts, and we run those prompts against third-party AI assistants and record the public answers over time so you can track how your brand appears.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">3. Permitted Use &amp; Account Responsibilities</h2>
            <p>
              You agree to use the service in compliance with all applicable laws. You are responsible for safeguarding your login credentials and for activity under your account. You agree not to abuse, overload, reverse-engineer, or resell the service, and not to use it for unlawful purposes.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">4. Third-Party AI Content &amp; Accuracy</h2>
            <p>
              Results are generated by independent third-party AI assistants that we do not control. AI answers are non-deterministic, may vary between runs, and can be incomplete or inaccurate. SlashSaaS reports these answers for informational purposes only and does not warrant their accuracy, completeness, or suitability for any decision.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">5. Availability &amp; Early Access</h2>
            <p>
              The service is provided on an &quot;as available&quot; basis and is under active development. Features, limits, and availability may change, and access may be interrupted, especially during early access. We aim to give reasonable notice of material changes.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">6. Subscriptions &amp; Payments</h2>
            <p>
              Paid plans, when offered, are sold and billed through LemonSqueezy, our authorized reseller and Merchant of Record, whose terms govern the transaction, taxes, and refunds. You may cancel a subscription at any time; access continues until the end of the current billing period.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">7. Intellectual Property</h2>
            <p>
              All software, design, logos, and materials provided by SlashSaaS remain the property of SlashSaaS. The monitoring configuration and results within your account remain yours; you grant us the permission needed to process them to provide the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">8. Disclaimer &amp; Limitation of Liability</h2>
            <p>
              The service is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind to the extent permitted by law. To the maximum extent permitted by law, SlashSaaS will not be liable for any indirect, incidental, or consequential damages, or for decisions made in reliance on AI-generated results.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">9. Termination &amp; Changes</h2>
            <p>
              You may stop using the service at any time. We may suspend or terminate accounts that abuse the service or violate these terms. We may update these terms from time to time; continued use after changes take effect constitutes acceptance.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">10. Contact &amp; Inquiries</h2>
            <p>
              For legal notices, terms questions, or inquiries:
            </p>
            <p className="text-xs text-[#8ce04a] font-mono">
              Email: support@slashsaas.com<br />
              Website: https://slashsaas.com
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
